[pytest]
log_cli = true
log_cli_level = INFO
log_cli_format = [%(asctime)s] [%(levelname)-7s] [%(name)s] - %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S

markers =
    p0: Priority 0 (Core) test cases
    p1: Priority 1 (Extended) test cases
    p2: Priority 2 (Advanced/Edge) test cases

testpaths =
    tests
